config/routes.rb
NewModels::Application.routes.draw do
  
  
  resources :myphotos

  resources :albums

  resources :historials

  resources :detallecompetencias

  resources :competencias

  resources :cotizaciones

  resources :lcotizas

  resources :fotos

  resources :telefonos

  resources :bookers

  resources :agenciamadres

  resources :agenciaextranjeras

  resources :clientes

  resources :caracteristicas

  resources :modelos
  resources :users
  resources :mantenedors 

  controller :home do
    get   'about'     => :about
    get   'password'  => :password
    post  'password'  => :password
    get   'logon'     => :index
    post  'logon'     => :logon
    get   'logoff'    => :logoff
  end

  root :to => "home#index"
  match "proyectos/:id/validate" => "proyectos#validate", :as => :validate_proyecto
  match "cotizaciones/:id/show_pdf" => "cotizaciones#show_pdf", :as => :show_pdf
  match 'javascripts/cliente(.:format)' => "javascripts#cliente"
  match 'javascripts/busca_cliente(.:format)' => "javascripts#busca_cliente"
  match 'javascripts/modelo(.:format)' => "javascripts#modelo"
  match 'javascripts/modelos(.:format)' => "javascripts#modelos"
  match 'busquedas/caracteristicas_modelo(.:format)' => "busquedas#caracteristicas_modelo", :as => :caracteristicas_modelo
  match 'busquedas/datos_modelos(.:format)' => "busquedas#datos_modelo", :as => :dato_modelo
  match 'competencias/:id/informe_comercial' => "competencias#informe_comercial", :as => :informe_comercial
  match 'competencias/:id/envio_mail' => "competencias#envio_mail", :as => :envio_mail
  match 'competencias/:id/excel' => "competencias#excel", :as => :excel
  match 'busquedas/envio_cotizacion(.:format)' => "busquedas#envio_cotizacion", :as => :envio_cotizacion
  match 'modelos/:id/subir_foto' => "modelos#subir_foto", :as => :subir_foto
  match 'modelos/:id/ver_album/:otro' => "modelos#ver_album", :as => :ver_album
  match 'reportes/informe_excel(.:format)' => "reportes#informe_excel", :as => :excel_informe
  match 'reportes/cotizacion_excel(.:format)' => "reportes#cotizacion_excel", :as => :excel_cotizacion
  

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  validates_presence_of :razonsocial, :direccion, :rut
  validates :rut, :uniqueness => {:scope => :rut}
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.xml
  load_and_authorize_resource
  def index
    @clientes =   paginamiento Cliente.where(:estado => nil).order("razonsocial ASC")
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.xml
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.xml
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.xml
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
      
        format.html { redirect_to(@cliente, :notice => 'Cliente fue creado Satisfactoriamente.') }
        format.xml  { render :xml => @cliente, :status => :created, :location => @cliente }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.xml
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to(@cliente, :notice => 'Cliente fue actualizado satisfactoriamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.xml
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.estado = 1
    @cliente.save
  
    respond_to do |format|
      format.html { redirect_to(clientes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.haml
- if @cliente.errors.any?
  #error_explanation
    %h2 #{@cliente.errors.count} errores impiden ingresar el Cliente:
    %ul
      - @cliente.errors.full_messages.each do |msg|
        %li= msg
%h1 Ingreso de Cliente
%table.sglea 
  %tr
    %td.tit Tipo Identificación
    %td.inp= manten f, :tipo_id, Mantenedor.tipoidentificacions, 'Seleccione por favor',{ :onchange => 'tipo_id_cliente(this);' }
    %td.tit Rut
    %td.inp= f.text_field :rut, :onblur => "upperCase(this);buscaClienteExiste(this);"
    %td.tit Razón Social
    %td.inp= f.text_field :razonsocial, :onblur => "upperCase(this)"
    %td.tit Nombre Fantasia
    %td.inp= f.text_field :nombrefantasia, :onblur => "upperCase(this)"
  %tr
    %td.tit Giro
    %td.inp= f.text_field :giro, :onblur => "upperCase(this)"
    %td.tit Dirección
    %td.inp= f.text_field :direccion, :onblur => "upperCase(this)"
    %td.tit Comuna
    %td.inp= f.text_field :comuna, :onblur => "upperCase(this)"
    %td.tit Ciudad
    %td.inp= f.text_field :ciudad, :onblur => "upperCase(this)"
  %tr
    %td.tit País
    %td.inp= manten f, :pais, Mantenedor.paises, 'Seleccione por favor'
    %td.tit Contacto
    %td.inp= f.text_field :contacto, :onblur => "upperCase(this)"
    %td.tit E-Mail
    %td.inp= f.text_field :email, :onblur => "upperCase(this)"
    %td.tit Número de Contacto
    %td.inp= f.text_field :ncontacto, :onblur => "upperCase(this)"
  %tr
    %td.tit Contacto Finanzas
    %td.inp= f.text_field :contactofinanzas, :onblur => "upperCase(this)"
    %td.tit Número de Contacto Finanzas
    %td.inp= f.text_field :ncontactofinanzas, :onblur => "upperCase(this)"
    %td.tit E-Mail Finanzas
    %td.inp= f.text_field :email_finanza, :onblur => "upperCase(this)"
    

app/views/clientes/edit.haml
- title "Modificación de Cliente "

= form_for @cliente, :html => { :multipart => true } do |f|
  = render 'form', :f => f, :form_disabled => false
  .actions{:align => "center"}
    = f.submit 'Modificar Cliente'

app/views/clientes/index.haml
%h2.titulo01 Listado de Clientes
= form_tag clientes_path, :method => 'get' do
  %p
    Paginación: #{select_paginacion @per_page}
= will_paginate @clientes
%table.sglea.datos
  %tr
    %td.titg Rut
    %td.titg Razón Social
    %td.titg Nombre Fantasia
    %td.titg Giro
    %td.titg Contacto
    %td.titg Telefono
    %td.titg Ver
    %td.titg Editar
    %td.titg Eliminar
  - @clientes.each do |cliente|
    %tr
      %td= cliente.rut
      %td= cliente.razonsocial
      %td= cliente.nombrefantasia
      %td= cliente.giro
      %td= cliente.contacto
      %td= cliente.ncontacto
      %td= link_to image_tag("ver.png"), cliente
      %td= link_to image_tag("editar.png"), edit_cliente_path(cliente)
      %td= link_to image_tag("eliminar.png"), cliente, :confirm => '¿Está Seguro?', :method => :delete
      
%br/
= link_button 'Agregar Cliente', new_cliente_path

app/views/clientes/new.haml
- title "Ingreso de Cliente"

= form_for @cliente, :html => { :multipart => true } do |f|
  = render 'form', :f => f, :form_disabled => false
  .actions{:align => "center"}
    = f.submit 'Ingresar Cliente'

app/views/clientes/show.haml
- title "Cliente "

= form_for @cliente, :builder => DisabledFormBuilder do |f|
  = render 'form', :f => f, :form_disabled => true