config/routes.rb
NewModels::Application.routes.draw do
  
  
  resources :myphotos

  resources :albums

  resources :historials

  resources :detallecompetencias

  resources :competencias

  resources :cotizaciones

  resources :lcotizas

  resources :fotos

  resources :telefonos

  resources :bookers

  resources :agenciamadres

  resources :agenciaextranjeras

  resources :clientes

  resources :caracteristicas

  resources :modelos
  resources :users
  resources :mantenedors 

  controller :home do
    get   'about'     => :about
    get   'password'  => :password
    post  'password'  => :password
    get   'logon'     => :index
    post  'logon'     => :logon
    get   'logoff'    => :logoff
  end

  root :to => "home#index"
  match "proyectos/:id/validate" => "proyectos#validate", :as => :validate_proyecto
  match "cotizaciones/:id/show_pdf" => "cotizaciones#show_pdf", :as => :show_pdf
  match 'javascripts/cliente(.:format)' => "javascripts#cliente"
  match 'javascripts/busca_cliente(.:format)' => "javascripts#busca_cliente"
  match 'javascripts/modelo(.:format)' => "javascripts#modelo"
  match 'javascripts/modelos(.:format)' => "javascripts#modelos"
  match 'busquedas/caracteristicas_modelo(.:format)' => "busquedas#caracteristicas_modelo", :as => :caracteristicas_modelo
  match 'busquedas/datos_modelos(.:format)' => "busquedas#datos_modelo", :as => :dato_modelo
  match 'competencias/:id/informe_comercial' => "competencias#informe_comercial", :as => :informe_comercial
  match 'competencias/:id/envio_mail' => "competencias#envio_mail", :as => :envio_mail
  match 'competencias/:id/excel' => "competencias#excel", :as => :excel
  match 'busquedas/envio_cotizacion(.:format)' => "busquedas#envio_cotizacion", :as => :envio_cotizacion
  match 'modelos/:id/subir_foto' => "modelos#subir_foto", :as => :subir_foto
  match 'modelos/:id/ver_album/:otro' => "modelos#ver_album", :as => :ver_album
  match 'reportes/informe_excel(.:format)' => "reportes#informe_excel", :as => :excel_informe
  match 'reportes/cotizacion_excel(.:format)' => "reportes#cotizacion_excel", :as => :excel_cotizacion
  

end

app/models/cotizacione.rb
class Cotizacione < ActiveRecord::Base
  has_many :lcotizas, :dependent => :destroy
  accepts_nested_attributes_for :lcotizas, :allow_destroy => true
  has_many :historials, :dependent => :destroy
  accepts_nested_attributes_for :historials, :allow_destroy => true  
  validates_presence_of :cliente, :presupuesto
end

app/controllers/cotizaciones_controller.rb
# -*- coding: utf-8 -*-
class CotizacionesController < ApplicationController
  # GET /cotizaciones
  # GET /cotizaciones.xml
   load_and_authorize_resource
  def index
    @cotizaciones = paginamiento Cotizacione.find(:all, :order => "id DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cotizaciones }
    end
  end

  # GET /cotizaciones/1
  # GET /cotizaciones/1.xml
  def show
    @cotizacione = Cotizacione.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cotizacione }
    end
  end
  
  # GET /cotizaciones/1
  # GET /cotizaciones/1.xml
  def show_pdf
    @cotizacione = Cotizacione.find(params[:id])
        
    respond_to do |format|
      format.html  { render :layout => nil }
      format.xml  { render :xml => @cotizacione }
    end

 
    
  end 
  

  # GET /cotizaciones/new
  # GET /cotizaciones/new.xml
  def new
    @cotizacione = Cotizacione.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cotizacione }
    end
  end

  # GET /cotizaciones/1/edit
  def edit
    @cotizacione = Cotizacione.find(params[:id])
   
  end

  # POST /cotizaciones
  # POST /cotizaciones.xml
  def create
    @cotizacione = Cotizacione.new(params[:cotizacione])
    
    #crear historial
    h = Historial.new
    h.usuario = current_user.nombre.to_s
    h.observacion = "Ha creado la Cotización"
    @cotizacione.historials << h


    respond_to do |format|
      if @cotizacione.save
        format.html { redirect_to(@cotizacione, :notice => 'La Cotización ha sido creada correctamente.') }
        format.xml  { render :xml => @cotizacione, :status => :created, :location => @cotizacione }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cotizacione.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cotizaciones/1
  # PUT /cotizaciones/1.xml
  def update
    @cotizacione = Cotizacione.find(params[:id])
   
    
    
    respond_to do |format|
      if @cotizacione.update_attributes(params[:cotizacione])
         
         
         #Actualizar historial
         h = Historial.new
         h.usuario = current_user.nombre.to_s
         h.observacion = "Ha Actualizado la Cotización - " + @cotizacione.obsedit
         @cotizacione.obsedit = ""
         @cotizacione.historials << h
         @cotizacione.save
         
        format.html { redirect_to(@cotizacione, :notice => 'La Cotización ha sido actualizada correctamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cotizacione.errors, :status => :unprocessable_entity }
      end
    end
  end


  
  # DELETE /cotizaciones/1
  # DELETE /cotizaciones/1.xml
  def destroy
    @cotizacione = Cotizacione.find(params[:id])
    @cotizacione.destroy

    respond_to do |format|
      format.html { redirect_to(cotizaciones_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/cotizaciones_helper.rb
module CotizacionesHelper
end

app/views/cotizaciones/_form.haml
- if @cotizacione.errors.any?
  #error_explanation
    %h2 #{@cotizacione.errors.count} errores impiden generar la Cotización:
    %ul
      - @cotizacione.errors.full_messages.each do |msg|
        %li= msg
%h1 Ingreso de Cotización
%table.sglea 
  %tr
    %td.tit Cliente
    %td.inp= f.text_field :cliente, :onblur => "upperCase(this)"
    %td.tit Fecha
    %td.inp= f.text_field :fecha, :size => 16
    :javascript
      $('#cotizacione_fecha').datetimepicker({
        timeText: 'Tiempo',
        hourText: 'hora',
        minuteText: 'min',
        stepMinute: 1,
        currentText: 'Fecha'
      });
    %td.tit Paises
    %td.inp= f.text_field :territorio, :onblur => "upperCase(this)"
  %tr
    %td.tit Jornada
    %td.inp= f.text_field :jornada, :onblur => "upperCase(this)"
    %td.tit Presupuesto
    %td.inp= f.text_field :presupuesto, :onblur => "upperCase(this)"
    %td.tit Exclusividad / Rubro
    %td.inp= f.text_field :exclusividad, :onblur => "upperCase(this)"
  %tr
    %td.tit Observaciones
    %td.inp= f.text_field :observaciones, :onblur => "upperCase(this)"
    %td.tit Reexhibicion
    %td.inp #{f.text_field :reexhibicion, :size => 1} %
    %td.tit Usuario
    - if f.object.usuario.nil?
      %td.inp= f.text_field :usuario, :value => current_user.nombre, :readonly => true
    - else
      %td.inp= f.text_field :usuario, :readonly => true
  %tr
    %td.tit Fecha de Trabajo INICIO
    %td.inp= f.text_field :fechatrabajo, :size => 16
    :javascript
      $('#cotizacione_fechatrabajo').datetimepicker({
        timeText: 'Tiempo',
        hourText: 'hora',
        minuteText: 'min',
        stepMinute: 1,
        currentText: 'Fecha'
      });
    %td.tit Fecha de Trabajo FIN
    %td.inp= f.text_field :fechatrabajofin, :size => 16
    :javascript
      $('#cotizacione_fechatrabajofin').datetimepicker({
        timeText: 'Tiempo',
        hourText: 'hora',
        minuteText: 'min',
        stepMinute: 1,
        currentText: 'Fecha'
      });
%br
%h2.titulo01 Detalles



.field
  = f.fields_for :lcotizas do |builder|
    = render 'lcotiza_fields', :f => builder, :form_disabled => form_disabled
= link_to_add_fields "Agregar", f, :lcotizas	 if not form_disabled

%h2.titulo02 Detalle de Modificaciones
%table.sglea.datos
  %tr
    %td.titg Fecha
    %td.titg Usuario
    %td.titg Observación
  - @cotizacione.historials.each do |h|
    %tr
      %td= h.created_at.try(:strftime, '%d-%m-%Y %H:%M')
      %td= h.usuario
      %td= h.observacion
%br/    
%br/
%br/    
%br/



  

app/views/cotizaciones/_lcotiza_fields.haml
.fields 
  = f.hidden_field :_destroy 
  %table.sglea
    %tr
      %td.titg Cantidad
      %td.titg Personaje
      %td.titg Rol
      %td.titg Tiempo
      %td.titg Medios
      %td.titg País
      %td.titg Valor
      %td.titg Día Adicional + IVA
      %td.titg Día Viajado + IVA

    %tr
      %td.inp= f.text_field :cantidad , :size => 1
      %td.inp= manten f, :personaje, Mantenedor.personajes, 'Seleccione por favor'
      %td.inp= manten f, :rol, Mantenedor.roles, 'Seleccione por favor'
      %td.inp Dias:#{f.text_field :tdia, :size => 1} Meses:#{f.text_field :tmes , :size => 1} Años:#{f.text_field :tanno , :size => 1}
      %td.inp= f.text_field  :medios, :size => 10,  :onblur => "upperCase(this)"
      %td.inp= f.text_field  :pais, :size => 10,  :onblur => "upperCase(this)"
      %td.inp= f.text_field :valor , :size => 5
      %td.inp= f.text_field :diaadicional, :size => 5	
      %td.inp= f.text_field :diaviajado, :size => 5
      %td.inp= link_to_remove_fields "X", f if not form_disabled
     

app/views/cotizaciones/edit.haml
- title "Modificación de Cotización "
%h2 Cotización Nº #{@cotizacione.id.to_s} 

= form_for @cotizacione, :html => { :multipart => true } do |f|
  = render 'form', :f => f, :form_disabled => false
  .actions{:align => "center"}
    Observación de la Modificación :
    = f.text_area :obsedit, :rows => 3, :cols => 50, :maxlength => 200, :onblur => "upperCase(this)"
    = f.submit 'Modificar Cotización'

app/views/cotizaciones/index.haml
%h2.titulo01 Listado de Cotizaciones
= form_tag cotizaciones_path, :method => 'get' do
  %p
    Paginación: #{select_paginacion @per_page}
= will_paginate @cotizaciones
%table.sglea.datos
  %tr
    %td.titg ID
    %td.titg Fecha
    %td.titg Cliente
    %td.titg Territorio
    %td.titg Jornada
    %td.titg Presupuesto
    %td.titg Exclusividad
    %td.titg Usuario
    %td.titg Ver
    %td.titg Editar
    %td.titg Eliminar
  - @cotizaciones.each do |cotizacione|
    %tr
      %td= cotizacione.id
      %td= cotizacione.fecha
      %td= cotizacione.cliente
      %td= cotizacione.territorio
      %td= cotizacione.jornada
      %td= number_to_currency(cotizacione.presupuesto, :locale => :clp, :precision => 0)
      %td= cotizacione.exclusividad
      %td= cotizacione.usuario
      %td= link_to image_tag("ver.png"), cotizacione
      %td= link_to image_tag("editar.png"), edit_cotizacione_path(cotizacione)
      %td= link_to image_tag("eliminar.png"), cotizacione, :confirm => '¿Está Seguro?', :method => :delete
      
%br/
= link_button 'Agregar Cotización', new_cotizacione_path

app/views/cotizaciones/new.haml
- title "Ingreso de Cotización"

= form_for @cotizacione, :html => { :multipart => true } do |f|
  = render 'form', :f => f, :form_disabled => false
  .actions{:align => "center"}
    = f.submit 'Ingresar Cotización'

app/views/cotizaciones/show.haml
:javascript
  $(document).ready(function(){
  	$("#form").submit(function () {
  		if($("#correo").val().length < 1) {
  			alert("La dirección e-mail es obligatoria");
  			return false;
  		}
  		if($("#correo").val().indexOf('@', 0) == -1 || $("#correo").val().indexOf('.', 0) == -1) {
  			alert("La dirección e-mail parece incorrecta");
  			return false;
  		}
  		return false;
  	});
  });

- title "Cotización "
%h2 Cotización Nº #{@cotizacione.id.to_s} 

= form_for @cotizacione, :builder => DisabledFormBuilder do |f|
  = render 'form', :f => f, :form_disabled => true
%br

%form{:id => "form", :action => "/busquedas/envio_cotizacion", :method => "get"}
  E-Mail destinatario :
  %input#correo{:name => "correo",:type => "text"}/
  %input#id{:name => "id",:type => "hidden", :value => @cotizacione.id}/
  %input{:type => "submit", :value => "Enviar Cotización" } 

app/views/cotizaciones/show_pdf.html.erb
<!-- Aca a poner logo -->
<img src="http://newmodels.luis-ramirez.cl/images/fondo-l.jpg" width="100">
<h3>COTIZACION NEW MODELS</h3>
<br/>
<table border="1" width="100%">
	<tr>
		<td width="200">Nombre de Cliente</td>
		<td width="400"><b><%=@cotizacione.cliente%></b></td>
		<td  width="200">Fecha de Cotización</td>
		<td width="400"><b><%=@cotizacione.fecha.try(:strftime, '%d/%m/%Y' )%></b></td>
	</tr>
	<tr>
		<td  width="200">Paises</td>
		<td width="400"><b><%=@cotizacione.territorio%></b></td>
		<td  width="200">Jornada</td>
		<td width="400"><b><%=@cotizacione.jornada%></b></td>
	</tr>
	<tr>
		<td width="200">Presupuesto</td>
		<td width="400"><b><%= number_to_currency(@cotizacione.presupuesto, :locale => :clp, :precision => 0) %></b></td>
		<td  width="200">Exclusividad / Rubro</td>
		<td  width="400"><b><%=@cotizacione.exclusividad%></b></td>
	</tr>
	<tr>
		<td width="200">Observaciones</td>
		<td ><b><%=@cotizacione.observaciones%></b></td>
		<td width="200">Reexhibición</td>
		<td width="400"><b><%=@cotizacione.reexhibicion%> %</b></td>
	</tr>
	<tr>
		<td>Fecha de Trabajo</td>
		<td><%=@cotizacione.fechatrabajo.try(:strftime, '%d/%m/%Y' )%></td>
	</tr>
</table>
<h4>DETALLE  DE LA COTIZACION</h4>
<table border="1" width="100%">
	<tr bgcolor="#798081">
		<td><b>Qtd</b></td>
		<td><b>Personaje</b></td>
		<td><b>Rol</b></td>
		<td><b>Tiempo</b></td>
		<td><b>Medios</b></td>
		<td><b>País</b></td>
		<td><b>Valor</b></td>
		<td><b>Día Adicional</b></td>
		<td><b>Día Viajado</b></td>
	</tr>
<% @cotizacione.lcotizas.each do |lcotiza| %>
  <tr>
    <td><%= lcotiza.cantidad %></td>
	<td><%= lcotiza.personaje %></td>
	<td><%= lcotiza.rol %></td>
	<td>D: <%= lcotiza.tdia %> M: <%= lcotiza.tmes %> A: <%= lcotiza.tanno %>   </td>
	<td><%= lcotiza.medios %></td>
	<td><%= lcotiza.pais %></td>
	<td><%= number_to_currency(lcotiza.valor, :locale => :clp, :precision => 0) %></td>
	<td><%= number_to_currency(lcotiza.diaadicional, :locale => :clp, :precision => 0) %></td>
	<td><%= number_to_currency(lcotiza.diaviajado, :locale => :clp, :precision => 0) %></td>
  </tr>
<% end %>
</table>
<p align="justify" ><strong>
	NOTAS: PRESUPUESTO CONSIDERA UNA JORNADA DE TOMAS FOTOGRÁFICAS. EN CASO DE SER RECHAZADAS Y/O NO PUBLICADAS LAS TOMAS REALIZADAS, SE DEBERÁ CANCELAR UN 50% SOBRE EL VALOR PACTADO POR NEW MODELS AGENCY LIMITADA, COMUNICANDO POR UN PLAZO DE 30 DIAS. DESPUES DE ESTE PLAZO EL CLIENTE DEBERA PAGAR EL 100% DEL PRESUPUESTO ORIGINAL.
</strong></p>
<p align="justify"><strong>
	EN CASO DE APROBAR PRESUPUESTO, SE RUEGA RE ENVIAR APROBACIÓN AL PRESENTE E-MAIL CON ESPECIFICACIONES DE CASTING (BOCETO) Y FECHAS PROBABLES PARA LAS TOMAS.-
</strong></p>
<!-- Aca a poner Firma -->
<p align="right">
<strong>
	<%= @cotizacione.usuario%><br>
	<% us = User.where(:nombre => @cotizacione.usuario) %>
	<%= us[0].cargo %>
</strong>	
</p>