config/routes.rb
NewModels::Application.routes.draw do
  
  
  resources :myphotos

  resources :albums

  resources :historials

  resources :detallecompetencias

  resources :competencias

  resources :cotizaciones

  resources :lcotizas

  resources :fotos

  resources :telefonos

  resources :bookers

  resources :agenciamadres

  resources :agenciaextranjeras

  resources :clientes

  resources :caracteristicas

  resources :modelos
  resources :users
  resources :mantenedors 

  controller :home do
    get   'about'     => :about
    get   'password'  => :password
    post  'password'  => :password
    get   'logon'     => :index
    post  'logon'     => :logon
    get   'logoff'    => :logoff
  end

  root :to => "home#index"
  match "proyectos/:id/validate" => "proyectos#validate", :as => :validate_proyecto
  match "cotizaciones/:id/show_pdf" => "cotizaciones#show_pdf", :as => :show_pdf
  match 'javascripts/cliente(.:format)' => "javascripts#cliente"
  match 'javascripts/busca_cliente(.:format)' => "javascripts#busca_cliente"
  match 'javascripts/modelo(.:format)' => "javascripts#modelo"
  match 'javascripts/modelos(.:format)' => "javascripts#modelos"
  match 'busquedas/caracteristicas_modelo(.:format)' => "busquedas#caracteristicas_modelo", :as => :caracteristicas_modelo
  match 'busquedas/datos_modelos(.:format)' => "busquedas#datos_modelo", :as => :dato_modelo
  match 'competencias/:id/informe_comercial' => "competencias#informe_comercial", :as => :informe_comercial
  match 'competencias/:id/envio_mail' => "competencias#envio_mail", :as => :envio_mail
  match 'competencias/:id/excel' => "competencias#excel", :as => :excel
  match 'busquedas/envio_cotizacion(.:format)' => "busquedas#envio_cotizacion", :as => :envio_cotizacion
  match 'modelos/:id/subir_foto' => "modelos#subir_foto", :as => :subir_foto
  match 'modelos/:id/ver_album/:otro' => "modelos#ver_album", :as => :ver_album
  match 'reportes/informe_excel(.:format)' => "reportes#informe_excel", :as => :excel_informe
  match 'reportes/cotizacion_excel(.:format)' => "reportes#cotizacion_excel", :as => :excel_cotizacion
  

end

app/models/myphoto.rb
class Myphoto < ActiveRecord::Base
   belongs_to :album
    mount_uploader :picture, ImageUploader  
end

app/controllers/myphotos_controller.rb
class MyphotosController < ApplicationController
  # GET /myphotos
  # GET /myphotos.xml
  def index
    @myphotos = Myphoto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @myphotos }
    end
  end

  # GET /myphotos/1
  # GET /myphotos/1.xml
  def show
    @myphoto = Myphoto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @myphoto }
    end
  end

  # GET /myphotos/new
  # GET /myphotos/new.xml
  def new
    @myphoto = Myphoto.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @myphoto }
    end
  end

  # GET /myphotos/1/edit
  def edit
    @myphoto = Myphoto.find(params[:id])
  end

  # POST /myphotos
  # POST /myphotos.xml
  def create
    @myphoto = Myphoto.new(params[:myphoto])

    respond_to do |format|
      if @myphoto.save
        format.html { redirect_to(@myphoto, :notice => 'Myphoto was successfully created.') }
        format.xml  { render :xml => @myphoto, :status => :created, :location => @myphoto }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @myphoto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /myphotos/1
  # PUT /myphotos/1.xml
  def update
    @myphoto = Myphoto.find(params[:id])

    respond_to do |format|
      if @myphoto.update_attributes(params[:myphoto])
        format.html { redirect_to(@myphoto, :notice => 'Myphoto was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @myphoto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /myphotos/1
  # DELETE /myphotos/1.xml
  def destroy
    @myphoto = Myphoto.find(params[:id])
    @myphoto.destroy

    respond_to do |format|
      format.html { redirect_to(myphotos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/myphotos_helper.rb
module MyphotosHelper
end

app/views/myphotos/_form.html.erb
<%= form_for @myphoto, :html => { :multipart => true } do |f|%>
  <% if @myphoto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myphoto.errors.count, "error") %> prohibited this myphoto from being saved:</h2>

      <ul>
      <% @myphoto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :observacion %><br />
    <%= f.text_field :observacion %>
  </div>
  <p>  
    <%= f.file_field :picture %>  
  </p>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myphotos/edit.html.erb
<h1>Editing myphoto</h1>

<%= render 'form' %>

<%= link_to 'Show', @myphoto %> |
<%= link_to 'Back', myphotos_path %>

app/views/myphotos/index.html.erb
<h1>Listing myphotos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Observacion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @myphotos.each do |myphoto| %>
  <tr>
    <td><%= myphoto.nombre %></td>
    <td><%= myphoto.observacion %></td>
    <td><%= link_to 'Show', myphoto %></td>
    <td><%= link_to 'Edit', edit_myphoto_path(myphoto) %></td>
    <td><%= link_to 'Destroy', myphoto, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Myphoto', new_myphoto_path %>

app/views/myphotos/new.html.erb
<h1>New myphoto</h1>

<%= render 'form' %>

<%= link_to 'Back', myphotos_path %>

app/views/myphotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @myphoto.nombre %>
</p>

<p>
  <b>Observacion:</b>
  <%= @myphoto.observacion %>
</p>


<%= link_to 'Edit', edit_myphoto_path(@myphoto) %> |
<%= link_to 'Back', myphotos_path %>