config/routes.rb
NewModels::Application.routes.draw do
  
  
  resources :myphotos

  resources :albums

  resources :historials

  resources :detallecompetencias

  resources :competencias

  resources :cotizaciones

  resources :lcotizas

  resources :fotos

  resources :telefonos

  resources :bookers

  resources :agenciamadres

  resources :agenciaextranjeras

  resources :clientes

  resources :caracteristicas

  resources :modelos
  resources :users
  resources :mantenedors 

  controller :home do
    get   'about'     => :about
    get   'password'  => :password
    post  'password'  => :password
    get   'logon'     => :index
    post  'logon'     => :logon
    get   'logoff'    => :logoff
  end

  root :to => "home#index"
  match "proyectos/:id/validate" => "proyectos#validate", :as => :validate_proyecto
  match "cotizaciones/:id/show_pdf" => "cotizaciones#show_pdf", :as => :show_pdf
  match 'javascripts/cliente(.:format)' => "javascripts#cliente"
  match 'javascripts/busca_cliente(.:format)' => "javascripts#busca_cliente"
  match 'javascripts/modelo(.:format)' => "javascripts#modelo"
  match 'javascripts/modelos(.:format)' => "javascripts#modelos"
  match 'busquedas/caracteristicas_modelo(.:format)' => "busquedas#caracteristicas_modelo", :as => :caracteristicas_modelo
  match 'busquedas/datos_modelos(.:format)' => "busquedas#datos_modelo", :as => :dato_modelo
  match 'competencias/:id/informe_comercial' => "competencias#informe_comercial", :as => :informe_comercial
  match 'competencias/:id/envio_mail' => "competencias#envio_mail", :as => :envio_mail
  match 'competencias/:id/excel' => "competencias#excel", :as => :excel
  match 'busquedas/envio_cotizacion(.:format)' => "busquedas#envio_cotizacion", :as => :envio_cotizacion
  match 'modelos/:id/subir_foto' => "modelos#subir_foto", :as => :subir_foto
  match 'modelos/:id/ver_album/:otro' => "modelos#ver_album", :as => :ver_album
  match 'reportes/informe_excel(.:format)' => "reportes#informe_excel", :as => :excel_informe
  match 'reportes/cotizacion_excel(.:format)' => "reportes#cotizacion_excel", :as => :excel_cotizacion
  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :proyectos_users
  has_many :proyectos, :through => :proyectos_users
  has_many :userroles
  has_many :roles, :through => :userroles
  
  def role_symbols
    roles.map do |role|
      role.nombre.underscore.tr(' ', '_').to_sym
    end
  end
  
  def role?(role)
    role_symbols.include? role
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  # cancan
  load_and_authorize_resource
  
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    ### cancan lo carga
    ###    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    ### cancan lo carga
    ###    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    ### cancan lo carga
    ###    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    ### cancan lo carga
    ###    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'Usuario fue creado correctamente.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    ### cancan lo carga
    ###    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User fue actualizado correctamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    ### cancan lo carga
    ###    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  %table.sglea
    %tr
      %td.tit Nombre
      %td.inp= f.text_field :nombre, :onblur => "upperCase(this)"
    %tr
      %td.tit Login
      %td.inp= f.text_field :login, :onblur => "upperCase(this)"
    %tr
      %td.tit Cargo
      %td.inp= f.text_field :cargo, :onblur => "upperCase(this)"
    %tr
      %td.tit Password
      %td.inp= f.password_field :password
    %tr
      %td.tit Confirmar Password
      %td.inp= f.password_field :password_confirmation
    %tr
      %td.tit Roles
      %td.inp
        - for role in Role.all
          %p
            = check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role), { :id => "user_role_ids_" + role.id.to_s }
            %label{:for => "user_role_ids_#{role.id}"}= role.nombre
    %tr
      %td= f.submit

app/views/users/edit.haml
%h2.titulo01 Editar usuario

= render 'form'

%br/
= link_button 'Ver', @user
= link_button 'Volver', users_path

app/views/users/index.haml
%h2.titulo01 Listado Usuarios

%table.sglea.datos
  %tr
    %td.titg Nombre
    %td.titg RUN o Login
    %td.titg Cargo
    %td.titg Roles
    %td.titg Ver
    %td.titg Editar
    %td.titg Borrar
  - @users.each do |user|
    %tr
      %td= user.nombre
      %td= user.login
      %td= user.cargo
      %td= user.roles.map(&:nombre).join(', ')
      %td= link_to image_tag("ver.png"), user
      %td= link_to image_tag("editar.png"), edit_user_path(user)
      %td= link_to image_tag("eliminar.png"), user, :confirm => '¿Está seguro?', :method => :delete

%br/
= link_button 'Nuevo Usuario', new_user_path

app/views/users/new.haml
%h2.titulo01 Crear Usuario

= render 'form'

%br/
= link_button 'Volver', users_path

app/views/users/show.haml
%h2.titulo01 Información Usuario

%table.sglea
  %tr
    %td.tit Nombre
    %td.inp= @user.nombre
  %tr
    %td.tit Login
    %td.inp= @user.login
  %tr
    %td.tit Cargo
    %td.inp= @user.cargo
  %tr
    %td.tit Roles
    %td.inp= @user.roles.map(&:nombre).join(', ')

%br/
= link_button 'Editar', edit_user_path(@user)
= link_button 'Volver', users_path